---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-suite

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: kube-suite
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-suite
  labels:
    k8s-app: fluentd
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd
      version: v1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluentd
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      # Enable tolerations if you want to run daemonset on master nodes.
      # Recommended to disable on managed k8s.
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.15-debian-graylog-1
          imagePullPolicy: IfNotPresent
          env:
            - name: FLUENT_GRAYLOG_HOST
              value: "graylog3"
            - name: FLUENT_GRAYLOG_PORT
              value: "12201"
            - name:  FLUENT_GRAYLOG_PROTOCOL
              value: "udp"
            - name: FLUENTD_SYSTEMD_CONF
              value: "disable"
            - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE 
              value: "cri"
          resources:
            requests:
              cpu: 200m
              memory: 0.5Gi
            limits:
            # ===========
            # Less memory leads to child process problems.
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            # - name: config-volume
            #   mountPath: /fluentd/etc/conf.d/multiline.conf
            #   subPath: multiline.conf
            - name: config-filter
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        # - name: config-volume
        #   configMap:
        #     name: fluentd-graylog-multiline-config
        #     items:
        #     - key: multiline.conf
        #       path: multiline.conf
        - name: config-filter
          configMap:
            name: fluentd-graylog-filter-config
            items:
            - key: fluent.conf
              path: fluent.conf
