apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox
    servicename: blackbox
  name: blackbox
  namespace: kube-suite
spec:
  type: NodePort
  ports:
  - name: http
    port: 9115
    targetPort: http
    nodePort: 30115
  selector:
    app: blackbox