apiVersion: v2
appVersion: 1.15.0
description: A Helm chart for Zadig
name: zadig
type: application
version: 1.15.1
dependencies:
- condition: tags.minio
  name: minio
  repository: https://charts.min.io/
  version: 4.0.15
- condition: tags.dex
  name: dex
  repository: https://charts.dexidp.io
  version: 0.6.3
- condition: tags.gloo
  name: gloo
  repository: https://storage.googleapis.com/solo-public-helm
  version: 1.9.1
- condition: tags.enterprise
  name: zadig-ee
  repository: ""
