apiVersion: v2
appVersion: 1.14.0
description: A Helm chart for Zadig
name: zadig
type: application
version: 1.14.1
dependencies:
- condition: tags.mongodb
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 10.29.0
- condition: tags.mysql
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 8.8.12
- condition: tags.dex
  name: dex
  repository: https://charts.dexidp.io
  version: 0.6.3
- condition: tags.gloo
  name: gloo
  repository: https://storage.googleapis.com/solo-public-helm
  version: 1.9.1
- condition: tags.ingressController
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 2.16.0
- condition: tags.minio
  name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 7.0.0