apiVersion: v2
appVersion: 1.13.0
description: A Helm chart for Zadig
name: zadig
type: application
version: 1.13.1
dependencies:
- name: dex
  repository: https://charts.dexidp.io
  version: 0.6.3
- name: gloo
  repository: https://storage.googleapis.com/solo-public-helm
  version: 1.9.1
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 2.16.0
  condition: tags.ingressController
- name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 7.0.0
  condition: tags.minio
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 10.29.0
  condition: tags.mongodb
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 8.8.12
  condition: tags.mysql
