apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy
  labels:
    {{- include "zadig.microservice.policy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.microservice.policy.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "zadig.microservice.policy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zadig.microservice.policy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zadig.serviceAccountName" .}}
      containers:
        - image: {{ .Values.microservice.policy.image.repository }}:{{ .Values.microservice.policy.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.microservice.policy.image.pullPolicy | default "Always" }}
          name: policy
          volumeMounts:
            - readOnly: true
              mountPath: /config
              name: policy-config
          env:
            - name: MONGODB_CONNECTION_STRING
              value: {{ .Values.connections.mongodb.connectionString }}
            - name: ASLAN_DB
              value: {{ .Values.connections.mongodb.db }}_policy
            - name: BE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - protocol: TCP
              containerPort: {{ template "zadig.microservice.policy.port" . }}
          resources:
          {{- if .Values.microservice.policy.resources }}
            {{ toYaml .Values.microservice.policy.resources | nindent 12 }}
          {{- else }}
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          {{- end }}
      volumes:
        - name: policy-config
          configMap:
            name: policy-config
