apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mysqlHost: {{ .Values.mysql.host | b64enc | quote }}
  mysqlPort: {{ .Values.mysql.port | b64enc | quote }}
  mysqlDatabase: {{ .Values.mysql.database | b64enc | quote }}
  mysqlUsername: {{ .Values.mysql.username | b64enc | quote }}
  mysqlPassword: {{ .Values.mysql.password | b64enc | quote }}
