apiVersion: v1
description: Helm chart for kruise components
home: https://openkruise.io
icon: http://openkruise.io/img/kruise_white.png
keywords:
- kubernetes
- kruise
- workload
- statefulset
- sidecar
- job
- deployment
name: kruise
sources:
- https://github.com/openkruise/kruise
version: 0.9.0
