apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  labels:
    {{- include "zadig.microservice.user.labels" . | nindent 4 }}
data:
  ADDRESS: {{ default "http" .Values.protocol }}://{{- include "zadig.endpoint" . }}
  ISSUER_URL: {{ .Values.dex.config.issuer }}
  CLIENT_ID: {{ (first .Values.dex.config.staticClients).id }}
  CLIENT_SECRET: {{ (first .Values.dex.config.staticClients).secret }}
  REDIRECT_URI: {{ (first (first .Values.dex.config.staticClients).redirectURIs) }}
  MYSQL_USER: {{ .Values.connections.mysql.auth.user }}
  MYSQL_PASSWORD: {{ .Values.connections.mysql.auth.password | quote }}
  MYSQL_HOST: {{ .Values.connections.mysql.host }}
  MYSQL_USER_DB: {{ .Values.microservice.user.database }}
  SCOPES: "openid,profile,email,offline_access,groups,federated:id"
  TOKEN_EXPIRES_AT: "1440"
