apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    {{- include "zadig.microservice.user.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.microservice.user.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "zadig.microservice.user.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zadig.microservice.user.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.microservice.user.image.repository }}:{{ .Values.microservice.user.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.microservice.user.image.pullPolicy | default "Always" }}
          name: user
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zadig-aes-key
                  key: aesKey
          envFrom:
            - configMapRef:
                name: user-config
          ports:
            - protocol: TCP
              containerPort: {{ template "zadig.microservice.user.port" . }}
          resources:
          {{- if .Values.microservice.user.resources }}
            {{ toYaml .Values.microservice.user.resources | nindent 12 }}
          {{- else }}
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          {{- end }}
