apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for Zadig Enterprise Edition
name: zadig-ee
type: application
version: 1.0.0
dependencies:
- name: minio
  condition: tags.minio
  repository: https://charts.min.io/
  version: 4.0.15
- name: dex
  condition: tags.dex
  repository: https://charts.dexidp.io
  version: 0.6.3
- name: gloo
  condition: tags.gloo
  repository: https://storage.googleapis.com/solo-public-helm
  version: 1.9.1
