apiVersion: v2
name: graylog
home: https://www.graylog.org
version: 2.1.3
appVersion: 4.2.7
description: Graylog is the centralized log management solution built to open standards for capturing, storing, and enabling real-time analysis of terabytes of machine data.
keywords:
  - graylog
  - logs
  - syslog
  - gelf
icon: https://global-uploads.webflow.com/5a218ef7897bf400019e2f16/5a218ef7897bf400019e2f60_logo-graylog.png
sources:
  - https://github.com/cacotopia/charts
maintainers:
  - name: cacotopia
    email: cacotopia@126.com
dependencies:
  - name: elasticsearch
    version: 7.10.2
    repository: https://helm.elastic.co
    tags:
      - elasticsearch
    condition: elasticsearch.enabled
  - name: mongodb
    version: 10.31.2
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mongodb
    condition: mongodb.enabled