apiVersion: apps/v1
kind: Deployment
metadata:
  name: picket
  labels:
    {{- include "zadig.microservice.picket.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.microservice.picket.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "zadig.microservice.picket.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zadig.microservice.picket.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.microservice.picket.image.repository }}:{{ .Values.microservice.picket.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.microservice.picket.image.pullPolicy | default "Always" }}
          name: picket
          ports:
            - protocol: TCP
              containerPort: {{ template "zadig.microservice.picket.port" . }}
          resources:
          {{- if .Values.microservice.picket.resources }}
            {{ toYaml .Values.microservice.picket.resources | nindent 12 }}
          {{- else }}
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          {{- end }}
