apiVersion: v1
kind: Service
metadata:
  name: podexec
  labels:
    {{- include "zadig.microservice.podexec.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ template "zadig.microservice.podexec.port" .}}
      targetPort: {{ template "zadig.microservice.podexec.port" .}}
  selector:
    {{- include "zadig.microservice.podexec.selectorLabels" . | nindent 4 }}