apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "zadig.pullSecretName" . }}
  labels:
    {{- include "zadig.labels" . | nindent 4 }}
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJjY3IuY2NzLnRlbmNlbnR5dW4uY29tIjp7ImF1dGgiOiJNVEF3TURFME9USTVPVFl6T201RGJXWlVRU3RaYW1oR01pcEROVW89In19fQ=="