apiVersion: v1
kind: Service
metadata:
  name: warpdrive
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zadig.microservice.warpdrive.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: warpdrive
      protocol: TCP
      port: {{ template "zadig.microservice.warpdrive.port" . }}
      targetPort: {{ template "zadig.microservice.warpdrive.port" . }}
  selector:
    {{- include "zadig.microservice.warpdrive.selectorLabels" . | nindent 4 }}
