apiVersion: v1
kind: Service
metadata:
  name: zadig-portal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zadig.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: portal
      port: 80
      targetPort: 80
  selector:
    {{- include "zadig.frontend.selectorLabels" . | nindent 4 }}