apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    {{- include "zadig.microservice.config.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.microservice.config.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "zadig.microservice.config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zadig.microservice.config.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.microservice.config.image.repository }}:{{ .Values.microservice.config.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.microservice.config.image.pullPolicy | default "Always" }}
          name: config
          env:
            - name: MYSQL_DEX_DB
              value: {{ .Values.microservice.config.dexDatabase }}
            - name: MYSQL_HOST
              value: {{ .Values.connections.mysql.host }}
            - name: MYSQL_USER
              value: {{ .Values.connections.mysql.auth.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.connections.mysql.auth.password }}
            - name: MONGODB_CONNECTION_STRING
              value: {{ .Values.connections.mongodb.connectionString }}
            - name: ASLAN_DB
              value: {{ .Values.connections.mongodb.db }}
          ports:
            - protocol: TCP
              containerPort: {{ template "zadig.microservice.config.port" . }}
          resources:
          {{- if .Values.microservice.config.resources }}
            {{ toYaml .Values.microservice.config.resources | nindent 12 }}
          {{- else }}
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- end }}
