{{- if .Values.initDB.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-init-db
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: mysql
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - name: import-nacos-mysql-sql
        image: {{ template "nacos.initDBImage" . }}
{{- include "nacos.imagePullSecrets" . | nindent 6 }}
        imagePullPolicy: {{ .Values.initDB.image.pullPolicy }}
        env: 
          - name: SQL_FILES
            valueFrom:
              configMapKeyRef:
                name: {{ template "nacos.fullname" . }}
                key: sql_files
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "nacos.fullname" . }}
                key: mysqlMasterHost
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: {{ template "nacos.fullname" . }}
                key: mysqlDatabase
          - name: MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: {{ template "nacos.fullname" . }}
                key: mysqlMasterPort
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "nacos.fullname" . }}
                key: mysqlMasterUser
          - name: MYSQL_PASSWD
            valueFrom:
              secretKeyRef:
                name: {{ template "nacos.fullname" . }}
                key: mysqlMasterPassword
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
  backoffLimit: 6
{{- end }}
